// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package v2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status_Response int32

const (
	Status_OK    Status_Response = 0
	Status_Error Status_Response = 1
)

var Status_Response_name = map[int32]string{
	0: "OK",
	1: "Error",
}

var Status_Response_value = map[string]int32{
	"OK":    0,
	"Error": 1,
}

func (x Status_Response) String() string {
	return proto.EnumName(Status_Response_name, int32(x))
}

func (Status_Response) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0, 0}
}

type Status struct {
	Code                 Status_Response `protobuf:"varint,1,opt,name=code,proto3,enum=v2.Status_Response" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() Status_Response {
	if m != nil {
		return m.Code
	}
	return Status_OK
}

type SearchKey struct {
	ApiVersion           string   `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchKey) Reset()         { *m = SearchKey{} }
func (m *SearchKey) String() string { return proto.CompactTextString(m) }
func (*SearchKey) ProtoMessage()    {}
func (*SearchKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *SearchKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchKey.Unmarshal(m, b)
}
func (m *SearchKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchKey.Marshal(b, m, deterministic)
}
func (m *SearchKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchKey.Merge(m, src)
}
func (m *SearchKey) XXX_Size() int {
	return xxx_messageInfo_SearchKey.Size(m)
}
func (m *SearchKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchKey.DiscardUnknown(m)
}

var xxx_messageInfo_SearchKey proto.InternalMessageInfo

func (m *SearchKey) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *SearchKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type Payload struct {
	ApiVersion           string   `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *Payload) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Payload) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("v2.Status_Response", Status_Response_name, Status_Response_value)
	proto.RegisterType((*Status)(nil), "v2.Status")
	proto.RegisterType((*SearchKey)(nil), "v2.SearchKey")
	proto.RegisterType((*Payload)(nil), "v2.Payload")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x18, 0xec, 0x3a, 0x8d, 0x21, 0x1f, 0x0d, 0xb2, 0x16, 0xa8, 0x22, 0x17, 0x90, 0xe5, 0x0b, 0x51,
	0x44, 0xd6, 0xc1, 0x1c, 0x40, 0x41, 0x48, 0xa4, 0x3f, 0x8a, 0xa0, 0x54, 0x18, 0x47, 0xe2, 0xbe,
	0x75, 0x3f, 0x5c, 0x83, 0xeb, 0xb5, 0xd6, 0x6b, 0x23, 0x5f, 0x91, 0x78, 0x01, 0x78, 0x34, 0x5e,
	0x81, 0x07, 0x41, 0x5e, 0x27, 0x34, 0x4a, 0xa5, 0xa2, 0x9e, 0xec, 0x9d, 0x6f, 0x66, 0xe7, 0x1b,
	0x8f, 0xa1, 0x5f, 0xa0, 0xac, 0x92, 0x08, 0x59, 0x2e, 0x85, 0x12, 0xd4, 0xa8, 0x7c, 0x7b, 0x2f,
	0x16, 0x22, 0x4e, 0xd1, 0xd3, 0xc8, 0x69, 0xf9, 0xd9, 0xc3, 0x8b, 0x5c, 0xd5, 0x2d, 0xc1, 0x7e,
	0xb8, 0x1c, 0xf2, 0x3c, 0xf1, 0x78, 0x96, 0x09, 0xc5, 0x55, 0x22, 0xb2, 0x62, 0x39, 0x7d, 0xaa,
	0x1f, 0xd1, 0x38, 0xc6, 0x6c, 0x5c, 0x7c, 0xe3, 0x71, 0x8c, 0xd2, 0x13, 0xb9, 0x66, 0x5c, 0x65,
	0xbb, 0x01, 0x98, 0x0b, 0xc5, 0x55, 0x59, 0xd0, 0x27, 0xb0, 0x1d, 0x89, 0x33, 0x1c, 0x10, 0x87,
	0x0c, 0xef, 0xfa, 0xf7, 0x58, 0xe5, 0xb3, 0x76, 0xc2, 0x42, 0x2c, 0x72, 0x91, 0x15, 0x18, 0x6a,
	0x82, 0xfb, 0x08, 0x6e, 0xaf, 0x10, 0x6a, 0x82, 0xf1, 0xe1, 0xd8, 0xda, 0xa2, 0x3d, 0xe8, 0x1e,
	0x49, 0x29, 0xa4, 0x45, 0xdc, 0xd7, 0xd0, 0x5b, 0x20, 0x97, 0xd1, 0xf9, 0x31, 0xd6, 0xf4, 0x31,
	0x00, 0xcf, 0x93, 0x4f, 0x28, 0x8b, 0x44, 0x64, 0xfa, 0xea, 0x5e, 0xb8, 0x86, 0x50, 0x0b, 0x3a,
	0x5f, 0xb1, 0x1e, 0x18, 0x0e, 0x19, 0xee, 0x84, 0xcd, 0xab, 0xfb, 0x11, 0x6e, 0x05, 0xbc, 0x4e,
	0x05, 0x3f, 0xbb, 0xb9, 0x98, 0xde, 0x87, 0x6e, 0xc5, 0xd3, 0x12, 0x07, 0x1d, 0x8d, 0xb5, 0x07,
	0xff, 0x47, 0x07, 0xba, 0x07, 0x3c, 0x3a, 0x47, 0xfa, 0x0a, 0x3a, 0x73, 0x54, 0xb4, 0xaf, 0xc3,
	0xad, 0x96, 0xb4, 0xef, 0x34, 0xc7, 0xa5, 0xa9, 0x3b, 0xf8, 0xfe, 0xfb, 0xcf, 0x2f, 0x83, 0xba,
	0x7d, 0xaf, 0xf2, 0xbd, 0xa8, 0x51, 0x79, 0x73, 0x54, 0x53, 0x32, 0xa2, 0xcf, 0xa0, 0xbf, 0x50,
	0x12, 0xf9, 0xc5, 0x1c, 0xd5, 0x09, 0xcf, 0xea, 0x6b, 0xaf, 0xd9, 0x1a, 0x92, 0x09, 0xa1, 0x2f,
	0x60, 0xe7, 0x9f, 0x64, 0x96, 0xa6, 0x74, 0x97, 0xb5, 0xd5, 0xb1, 0x55, 0xaf, 0xec, 0xa8, 0xe9,
	0x75, 0x43, 0x3a, 0x21, 0x74, 0x08, 0xbd, 0x56, 0x18, 0x94, 0x8a, 0xae, 0x4f, 0x6d, 0xb8, 0x2c,
	0xa6, 0x31, 0xa1, 0x2f, 0xa1, 0x73, 0x2d, 0x67, 0x99, 0xc7, 0x5e, 0xcb, 0x13, 0x94, 0x3a, 0xcf,
	0x78, 0xb5, 0xdc, 0x21, 0xa6, 0xa8, 0x70, 0x33, 0xce, 0xa6, 0xd1, 0x1b, 0x30, 0xff, 0x4f, 0xdc,
	0xd3, 0x6e, 0x0f, 0x46, 0xd6, 0xa5, 0x5b, 0x2b, 0x9a, 0x92, 0xd1, 0xfe, 0xc9, 0xcf, 0xd9, 0x3b,
	0xea, 0xc0, 0xee, 0x3c, 0x0c, 0x0e, 0x9c, 0xf7, 0x58, 0x61, 0x7a, 0xb8, 0xef, 0xe8, 0x62, 0x9c,
	0x59, 0xf0, 0xd6, 0x37, 0x2b, 0x9f, 0x4d, 0xd8, 0x64, 0x64, 0x18, 0xdb, 0xbe, 0xc5, 0xf3, 0x3c,
	0x4d, 0x22, 0xfd, 0xab, 0x7a, 0x5f, 0x0a, 0x91, 0x4d, 0xaf, 0x20, 0xa7, 0xa6, 0xfe, 0x88, 0xcf,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x6f, 0x36, 0xc4, 0x3f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CacheClient is the client API for Cache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CacheClient interface {
	Get(ctx context.Context, in *SearchKey, opts ...grpc.CallOption) (*Payload, error)
	StreamGetMany(ctx context.Context, opts ...grpc.CallOption) (Cache_StreamGetManyClient, error)
	StreamGetAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Cache_StreamGetAllClient, error)
	StreamPut(ctx context.Context, opts ...grpc.CallOption) (Cache_StreamPutClient, error)
	Put(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Status, error)
	StreamDelete(ctx context.Context, opts ...grpc.CallOption) (Cache_StreamDeleteClient, error)
	Delete(ctx context.Context, in *SearchKey, opts ...grpc.CallOption) (*Status, error)
}

type cacheClient struct {
	cc *grpc.ClientConn
}

func NewCacheClient(cc *grpc.ClientConn) CacheClient {
	return &cacheClient{cc}
}

func (c *cacheClient) Get(ctx context.Context, in *SearchKey, opts ...grpc.CallOption) (*Payload, error) {
	out := new(Payload)
	err := c.cc.Invoke(ctx, "/v2.Cache/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) StreamGetMany(ctx context.Context, opts ...grpc.CallOption) (Cache_StreamGetManyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Cache_serviceDesc.Streams[0], "/v2.Cache/StreamGetMany", opts...)
	if err != nil {
		return nil, err
	}
	x := &cacheStreamGetManyClient{stream}
	return x, nil
}

type Cache_StreamGetManyClient interface {
	Send(*SearchKey) error
	Recv() (*Payload, error)
	grpc.ClientStream
}

type cacheStreamGetManyClient struct {
	grpc.ClientStream
}

func (x *cacheStreamGetManyClient) Send(m *SearchKey) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cacheStreamGetManyClient) Recv() (*Payload, error) {
	m := new(Payload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cacheClient) StreamGetAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Cache_StreamGetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Cache_serviceDesc.Streams[1], "/v2.Cache/StreamGetAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &cacheStreamGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cache_StreamGetAllClient interface {
	Recv() (*Payload, error)
	grpc.ClientStream
}

type cacheStreamGetAllClient struct {
	grpc.ClientStream
}

func (x *cacheStreamGetAllClient) Recv() (*Payload, error) {
	m := new(Payload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cacheClient) StreamPut(ctx context.Context, opts ...grpc.CallOption) (Cache_StreamPutClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Cache_serviceDesc.Streams[2], "/v2.Cache/StreamPut", opts...)
	if err != nil {
		return nil, err
	}
	x := &cacheStreamPutClient{stream}
	return x, nil
}

type Cache_StreamPutClient interface {
	Send(*Payload) error
	CloseAndRecv() (*Status, error)
	grpc.ClientStream
}

type cacheStreamPutClient struct {
	grpc.ClientStream
}

func (x *cacheStreamPutClient) Send(m *Payload) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cacheStreamPutClient) CloseAndRecv() (*Status, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Status)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cacheClient) Put(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/v2.Cache/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) StreamDelete(ctx context.Context, opts ...grpc.CallOption) (Cache_StreamDeleteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Cache_serviceDesc.Streams[3], "/v2.Cache/StreamDelete", opts...)
	if err != nil {
		return nil, err
	}
	x := &cacheStreamDeleteClient{stream}
	return x, nil
}

type Cache_StreamDeleteClient interface {
	Send(*SearchKey) error
	CloseAndRecv() (*Status, error)
	grpc.ClientStream
}

type cacheStreamDeleteClient struct {
	grpc.ClientStream
}

func (x *cacheStreamDeleteClient) Send(m *SearchKey) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cacheStreamDeleteClient) CloseAndRecv() (*Status, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Status)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cacheClient) Delete(ctx context.Context, in *SearchKey, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/v2.Cache/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheServer is the server API for Cache service.
type CacheServer interface {
	Get(context.Context, *SearchKey) (*Payload, error)
	StreamGetMany(Cache_StreamGetManyServer) error
	StreamGetAll(*empty.Empty, Cache_StreamGetAllServer) error
	StreamPut(Cache_StreamPutServer) error
	Put(context.Context, *Payload) (*Status, error)
	StreamDelete(Cache_StreamDeleteServer) error
	Delete(context.Context, *SearchKey) (*Status, error)
}

func RegisterCacheServer(s *grpc.Server, srv CacheServer) {
	s.RegisterService(&_Cache_serviceDesc, srv)
}

func _Cache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.Cache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Get(ctx, req.(*SearchKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_StreamGetMany_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CacheServer).StreamGetMany(&cacheStreamGetManyServer{stream})
}

type Cache_StreamGetManyServer interface {
	Send(*Payload) error
	Recv() (*SearchKey, error)
	grpc.ServerStream
}

type cacheStreamGetManyServer struct {
	grpc.ServerStream
}

func (x *cacheStreamGetManyServer) Send(m *Payload) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cacheStreamGetManyServer) Recv() (*SearchKey, error) {
	m := new(SearchKey)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Cache_StreamGetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CacheServer).StreamGetAll(m, &cacheStreamGetAllServer{stream})
}

type Cache_StreamGetAllServer interface {
	Send(*Payload) error
	grpc.ServerStream
}

type cacheStreamGetAllServer struct {
	grpc.ServerStream
}

func (x *cacheStreamGetAllServer) Send(m *Payload) error {
	return x.ServerStream.SendMsg(m)
}

func _Cache_StreamPut_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CacheServer).StreamPut(&cacheStreamPutServer{stream})
}

type Cache_StreamPutServer interface {
	SendAndClose(*Status) error
	Recv() (*Payload, error)
	grpc.ServerStream
}

type cacheStreamPutServer struct {
	grpc.ServerStream
}

func (x *cacheStreamPutServer) SendAndClose(m *Status) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cacheStreamPutServer) Recv() (*Payload, error) {
	m := new(Payload)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Cache_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Payload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.Cache/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Put(ctx, req.(*Payload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_StreamDelete_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CacheServer).StreamDelete(&cacheStreamDeleteServer{stream})
}

type Cache_StreamDeleteServer interface {
	SendAndClose(*Status) error
	Recv() (*SearchKey, error)
	grpc.ServerStream
}

type cacheStreamDeleteServer struct {
	grpc.ServerStream
}

func (x *cacheStreamDeleteServer) SendAndClose(m *Status) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cacheStreamDeleteServer) Recv() (*SearchKey, error) {
	m := new(SearchKey)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Cache_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.Cache/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Delete(ctx, req.(*SearchKey))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v2.Cache",
	HandlerType: (*CacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Cache_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Cache_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Cache_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamGetMany",
			Handler:       _Cache_StreamGetMany_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamGetAll",
			Handler:       _Cache_StreamGetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPut",
			Handler:       _Cache_StreamPut_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamDelete",
			Handler:       _Cache_StreamDelete_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
