# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rservice.proto\x12\x02v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"J\n\x06Status\x12!\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x13.v1.Status.Response\"\x1d\n\x08Response\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45rror\x10\x01\"\x18\n\tSearchKey\x12\x0b\n\x03key\x18\x01 \x01(\t\"%\n\x07Payload\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2\xdf\x02\n\x05\x43\x61\x63he\x12>\n\x03Get\x12\r.v1.SearchKey\x1a\x0b.v1.Payload\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/cache/Get/{key}\x12I\n\x07GetMany\x12\r.v1.SearchKey\x1a\x0b.v1.Payload\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x11/v1/cache/GetMany:\x03key(\x01\x30\x01\x12I\n\x06GetAll\x12\x16.google.protobuf.Empty\x1a\x0b.v1.Payload\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/cache/GetAll0\x01\x12:\n\x03Put\x12\x0b.v1.Payload\x1a\n.v1.Status\"\x18\x82\xd3\xe4\x93\x02\x12\x1a\r/v1/cache/Put:\x01*(\x01\x12\x44\n\x06\x44\x65lete\x12\r.v1.SearchKey\x1a\n.v1.Status\"\x1d\x82\xd3\xe4\x93\x02\x17\"\x10/v1/cache/Delete:\x03key(\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])



_STATUS_RESPONSE = _descriptor.EnumDescriptor(
  name='Response',
  full_name='v1.Status.Response',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Error', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=125,
  serialized_end=154,
)
_sym_db.RegisterEnumDescriptor(_STATUS_RESPONSE)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='v1.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='v1.Status.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATUS_RESPONSE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=154,
)


_SEARCHKEY = _descriptor.Descriptor(
  name='SearchKey',
  full_name='v1.SearchKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='v1.SearchKey.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=180,
)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='v1.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='v1.Payload.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='v1.Payload.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=219,
)

_STATUS.fields_by_name['code'].enum_type = _STATUS_RESPONSE
_STATUS_RESPONSE.containing_type = _STATUS
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['SearchKey'] = _SEARCHKEY
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:v1.Status)
  ))
_sym_db.RegisterMessage(Status)

SearchKey = _reflection.GeneratedProtocolMessageType('SearchKey', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHKEY,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:v1.SearchKey)
  ))
_sym_db.RegisterMessage(SearchKey)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:v1.Payload)
  ))
_sym_db.RegisterMessage(Payload)



_CACHE = _descriptor.ServiceDescriptor(
  name='Cache',
  full_name='v1.Cache',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=222,
  serialized_end=573,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='v1.Cache.Get',
    index=0,
    containing_service=None,
    input_type=_SEARCHKEY,
    output_type=_PAYLOAD,
    serialized_options=_b('\202\323\344\223\002\025\022\023/v1/cache/Get/{key}'),
  ),
  _descriptor.MethodDescriptor(
    name='GetMany',
    full_name='v1.Cache.GetMany',
    index=1,
    containing_service=None,
    input_type=_SEARCHKEY,
    output_type=_PAYLOAD,
    serialized_options=_b('\202\323\344\223\002\030\"\021/v1/cache/GetMany:\003key'),
  ),
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='v1.Cache.GetAll',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_PAYLOAD,
    serialized_options=_b('\202\323\344\223\002\022\022\020/v1/cache/GetAll'),
  ),
  _descriptor.MethodDescriptor(
    name='Put',
    full_name='v1.Cache.Put',
    index=3,
    containing_service=None,
    input_type=_PAYLOAD,
    output_type=_STATUS,
    serialized_options=_b('\202\323\344\223\002\022\032\r/v1/cache/Put:\001*'),
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='v1.Cache.Delete',
    index=4,
    containing_service=None,
    input_type=_SEARCHKEY,
    output_type=_STATUS,
    serialized_options=_b('\202\323\344\223\002\027\"\020/v1/cache/Delete:\003key'),
  ),
])
_sym_db.RegisterServiceDescriptor(_CACHE)

DESCRIPTOR.services_by_name['Cache'] = _CACHE

# @@protoc_insertion_point(module_scope)
